In [1]:
import plotly.express as px
import pandas as pd
import numpy as np
import sklearn as sn
import matplotlib as mp
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
pip install xlrd

Requirement already satisfied: xlrd in c:\users\admin\anaconda3\lib\site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [32]:
df=pd.read_excel("C:\\Users\\Admin\\peters project\\GCP.xlsx", header=0, skiprows=1)
df.head(10)

,Coun- ty Code,County Name,"Agriculture, forestry and fishing",Mining and quarrying,Manufacturing,Electricity supply,Water supply; waste collection,Construction,Wholesale and retail trade; repair of motor vehicles,Transport and storage,...,Informa- tion and communi- cation,Financial and insurance activities,Real estate activities,"Profes- sional, technical and support services",Public admin- istration and defence,Education,Human health and social work activities,Other service activities,FISIM1,Total
0,1,MOMBASA,1459,1158,47348,20546,1078,37168,36912,88308,...,5413,31155,35526,7124,12024,4229,4539,2379,-17026,332122
1,2,KWALE,39610,1447,300,730,513,3184,5051,4198,...,879,4941,5733,349,4566,5384,1575,1647,-526,86278
2,3,KILIFI,38319,3334,8456,1471,1353,2233,6037,11411,...,2423,8659,14511,286,6452,9219,2539,2810,-1329,119295
3,4,TANA RIVER,18333,57,11,73,2199,24,3024,924,...,327,2188,752,1,3138,1501,451,608,-158,33498
4,5,LAMU,18699,126,48,340,90,172,2864,4171,...,287,716,1195,10,2129,923,272,257,-167,32386
5,6,TAITA TAVETA,19858,727,101,567,337,2188,5607,3109,...,559,4504,3988,8,5145,2463,813,721,-393,51381
6,7,GARISSA,16845,559,1153,318,174,1481,2496,1410,...,324,260,2586,73,6780,3388,908,881,-358,39394
7,8,WAJIR,20032,450,15,22,170,2805,2065,258,...,144,1527,767,3,5150,1960,900,936,-108,37159
8,9,MANDERA,14169,178,28,581,256,2512,1966,1155,...,292,1388,3091,4,4723,2643,645,1450,-78,35101
9,10,MARSABIT,16078,72,13,259,233,7311,1257,337,...,300,320,2045,26,3113,1502,659,650,-169,34073

In [33]:
list(df.columns)

['Coun- ty Code',
 'County Name',
 'Agriculture, forestry and fishing',
 'Mining and quarrying',
 'Manufacturing',
 'Electricity supply',
 'Water supply; waste collection',
 'Construction',
 'Wholesale and retail trade; repair of motor vehicles',
 'Transport and storage',
 'Accom- modation and food service activities',
 'Informa- tion and communi- cation',
 'Financial and insurance activities',
 'Real estate activities',
 'Profes- sional, technical and support services',
 'Public admin- istration and defence',
 'Education',
 'Human health and social work activities',
 'Other service activities',
 'FISIM1',
 'Total']

In [40]:
df.columns.unique

<bound method Index.unique of Index(['Coun- ty Code', 'County Name', 'Agriculture, forestry and fishing',
       'Mining and quarrying', 'Manufacturing', 'Electricity supply',
       'Water supply; waste collection', 'Construction',
       'Wholesale and retail trade; repair of motor vehicles',
       'Transport and storage', 'Accom- modation and food service activities',
       'Informa- tion and communi- cation',
       'Financial and insurance activities', 'Real estate activities',
       'Profes- sional, technical and support services',
       'Public admin- istration and defence', 'Education',
       'Human health and social work activities', 'Other service activities',
       'FISIM1', 'Total'],
      dtype='object')>

In [41]:
pip install geopandas

Requirement already satisfied: geopandas in c:\users\admin\anaconda3\lib\site-packages (0.14.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: pandas>=1.4.0 in c:\users\admin\anaconda3\lib\site-packages (from geopandas) (1.4.4)
Requirement already satisfied: shapely>=1.8.0 in c:\users\admin\anaconda3\lib\site-packages (from geopandas) (2.0.3)
Requirement already satisfied: packaging in c:\users\admin\anaconda3\lib\site-packages (from geopandas) (21.3)
Requirement already satisfied: fiona>=1.8.21 in c:\users\admin\anaconda3\lib\site-packages (from geopandas) (1.9.6)
Requirement already satisfied: pyproj>=3.3.0 in c:\users\admin\anaconda3\lib\site-packages (from geopandas) (3.6.1)
Requirement already satisfied: click-plugins>=1.0 in c:\users\admin\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (1.1.1)
Requirement already satisfied: click~=8.0 in c:\users\admin\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (8.0.4)
Requirement already satisfied: importlib-metadata in c:\users\admin\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (4.11.3)
Requirement already satisfied: attrs>=19.2.0 in c:\users\admin\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (21.4.0)
Requirement already satisfied: cligj>=0.5 in c:\users\admin\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (0.7.2)
Requirement already satisfied: six in c:\users\admin\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (1.16.0)
Requirement already satisfied: certifi in c:\users\admin\anaconda3\lib\site-packages (from fiona>=1.8.21->geopandas) (2022.9.14)
Requirement already satisfied: numpy>=1.18.5 in c:\users\admin\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas>=1.4.0->geopandas) (2022.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\admin\anaconda3\lib\site-packages (from packaging->geopandas) (3.0.9)
Requirement already satisfied: colorama in c:\users\admin\anaconda3\lib\site-packages (from click~=8.0->fiona>=1.8.21->geopandas) (0.4.5)
Requirement already satisfied: zipp>=0.5 in c:\users\admin\anaconda3\lib\site-packages (from importlib-metadata->fiona>=1.8.21->geopandas) (3.8.0)

In [42]:
import geopandas as gpd

In [43]:
geo_df = gpd.read_file("C:\\Users\\Admin\\peters project\\County.shp")

In [44]:
geo_df.head(55)

,OBJECTID,AREA,PERIMETER,COUNTY3_,COUNTY3_ID,COUNTY,Shape_Leng,Shape_Area,geometry
0,1,5.677,15.047,2.0,1.0,Turkana,15.046838,5.676985,"POLYGON ((35.79593 5.34449, 35.79659 5.34468, ..."
1,2,6.177,11.974,3.0,2.0,Marsabit,11.974165,6.176831,"POLYGON ((36.05061 4.45622, 36.23184 4.45124, ..."
2,3,2.117,7.355,4.0,3.0,Mandera,7.355154,2.117196,"POLYGON ((41.62133 3.97673, 41.62272 3.97860, ..."
3,4,4.610,9.838,5.0,4.0,Wajir,9.838408,4.609589,"POLYGON ((39.31812 3.47197, 39.31956 3.47168, ..."
4,5,0.740,5.030,6.0,5.0,West Pokot,5.030271,0.740481,"POLYGON ((35.12745 2.62271, 35.12762 2.62302, ..."
5,6,1.713,8.311,7.0,6.0,Samburu,8.311013,1.713014,"POLYGON ((36.73652 2.51379, 36.73706 2.51398, ..."
6,7,2.060,10.181,8.0,7.0,Isiolo,10.181411,2.059820,"POLYGON ((37.94529 1.26288, 38.33966 1.57742, ..."
7,8,0.877,5.964,9.0,8.0,Baringo,5.964266,0.877177,"POLYGON ((35.70707 1.42160, 35.70693 1.42253, ..."
8,9,0.245,4.064,10.0,9.0,Keiyo-Marakwet,4.063527,0.245208,"POLYGON ((35.70280 1.24649, 35.70271 1.24591, ..."
9,10,0.202,2.387,11.0,10.0,Trans Nzoia,2.387265,0.201983,"POLYGON ((34.82016 1.25983, 34.82024 1.26042, ..."
10,11,0.246,3.076,12.0,11.0,Bungoma,3.075944,0.245741,"POLYGON ((34.58077 1.15033, 34.61261 1.10971, ..."
11,12,3.642,11.281,13.0,12.0,Garissa,11.281126,3.641823,"POLYGON ((39.29730 0.90783, 39.30076 0.91194, ..."
12,13,0.272,3.718,14.0,13.0,Uasin Gishu,3.717922,0.271894,"POLYGON ((35.35963 0.94435, 35.37798 0.93534, ..."
13,14,0.243,4.089,15.0,14.0,Kakamega,4.089310,0.242844,"POLYGON ((35.01771 0.88754, 35.01768 0.88777, ..."
14,15,0.787,5.359,16.0,15.0,Laikipia,5.358738,0.786753,"POLYGON ((36.48872 0.84680, 36.48873 0.84654, ..."
15,16,0.148,2.683,17.0,16.0,Busia,2.682712,0.147514,"POLYGON ((34.43332 0.73570, 34.43318 0.73520, ..."
16,17,0.561,4.285,18.0,17.0,Meru,4.284992,0.560550,"POLYGON ((38.25489 0.19919, 38.25550 0.19870, ..."
17,18,0.233,2.987,19.0,18.0,Nandi,2.986884,0.233172,"POLYGON ((34.85030 0.54573, 35.04440 0.56148, ..."
18,19,0.285,2.925,20.0,19.0,Siaya,2.924506,0.285189,"POLYGON ((34.37066 0.30656, 34.38985 0.28960, ..."
19,20,0.605,6.475,21.0,20.0,Nakuru,6.474904,0.604913,"POLYGON ((36.25549 -0.02196, 36.25241 -0.03496..."
20,21,0.045,1.365,22.0,21.0,Vihiga,1.364576,0.045428,"POLYGON ((34.92514 0.19919, 34.91594 0.17175, ..."
21,22,0.266,3.588,23.0,22.0,Nyandarua,3.587821,0.265942,"POLYGON ((36.65747 -0.15308, 36.68586 -0.17446..."
22,23,0.217,3.091,24.0,23.0,Tharaka,3.090717,0.216960,"POLYGON ((38.18547 0.01950, 38.18560 0.01921, ..."
23,24,0.171,2.980,25.0,24.0,Kericho,2.979811,0.170724,"POLYGON ((35.43483 0.02547, 35.43512 0.02543, ..."
24,25,0.217,3.115,26.0,25.0,Kisumu,3.115223,0.217291,"POLYGON ((34.53411 -0.01537, 34.53706 -0.01567..."
25,26,0.271,3.050,27.0,26.0,Nyeri,3.050349,0.270857,"POLYGON ((37.30779 -0.15107, 37.20803 -0.41031..."
26,27,3.074,11.603,28.0,27.0,Tana River,11.603081,3.074107,"POLYGON ((38.76868 -0.06875, 38.77035 -0.06899..."
27,28,2.483,9.029,29.0,28.0,Kitui,9.028668,2.483477,"POLYGON ((38.43415 -0.07482, 38.82981 -0.76018..."
28,29,0.120,1.875,30.0,29.0,Kirinyaga,1.874547,0.120010,"POLYGON ((37.42641 -0.51109, 37.42685 -0.51168..."
29,30,0.230,3.339,31.0,30.0,Embu,3.339148,0.229668,"POLYGON ((37.92902 -0.42571, 37.92938 -0.42533..."
30,31,0.386,3.410,32.0,31.0,Homa Bay,3.410303,0.386329,"POLYGON ((34.48342 -0.29927, 34.53242 -0.27171..."
31,32,0.229,2.632,33.0,32.0,Bomet,2.631657,0.229037,"POLYGON ((35.32763 -0.40701, 35.32771 -0.40674..."
32,33,0.072,1.505,34.0,33.0,Nyamira,1.504872,0.071882,"POLYGON ((35.05135 -0.49959, 35.05145 -0.49993..."
33,34,1.454,6.862,35.0,34.0,Narok,6.861770,1.454091,"POLYGON ((35.68982 -0.60552, 35.69005 -0.60528..."
34,35,0.106,1.677,36.0,35.0,Kisii,1.676940,0.106043,"POLYGON ((34.86206 -0.50133, 34.86307 -0.50280..."
35,36,0.206,2.537,37.0,36.0,Murang'a,2.536662,0.206462,"POLYGON ((36.88600 -0.60966, 36.88634 -0.60962..."
36,37,0.257,3.012,38.0,37.0,Migori,3.011590,0.257126,"POLYGON ((34.63766 -0.66513, 34.63659 -0.67013..."
37,38,0.209,3.086,39.0,38.0,Kiambu,3.085721,0.209126,"POLYGON ((36.55285 -0.92000, 36.56864 -0.91107..."
38,39,0.506,5.792,40.0,39.0,Machakos,5.792040,0.505507,"POLYGON ((37.28101 -0.78417, 37.28164 -0.78399..."
39,40,1.774,7.280,41.0,40.0,Kajiado,7.280366,1.774001,"POLYGON ((36.33392 -1.04937, 36.48927 -1.12253..."
40,41,0.057,1.616,42.0,41.0,Nairobi,1.615813,0.057278,"POLYGON ((37.10272 -1.26172, 37.10276 -1.26197..."
41,42,0.649,5.754,43.0,42.0,Makueni,5.753765,0.649311,"POLYGON ((37.54930 -1.53775, 37.55000 -1.53811..."
42,43,0.484,7.490,44.0,43.0,Lamu,11.268309,0.501665,"MULTIPOLYGON (((40.71307 -2.29510, 40.71350 -2..."
43,110,1.016,6.220,111.0,110.0,Kilifi,6.858123,1.017021,"MULTIPOLYGON (((39.96851 -3.39301, 39.96808 -3..."
44,111,1.396,5.573,112.0,111.0,Taita Taveta,5.572639,1.395854,"POLYGON ((38.54604 -2.97978, 38.54692 -2.97989..."
45,135,0.670,4.994,136.0,135.0,Kwale,5.646620,0.671356,"MULTIPOLYGON (((39.40649 -4.70221, 39.40588 -4..."
46,141,0.001,0.177,142.0,141.0,Mombasa,1.979026,0.018444,"MULTIPOLYGON (((39.58429 -4.11780, 39.57849 -4..."

In [45]:
list(geo_df.columns)

['OBJECTID',
 'AREA',
 'PERIMETER',
 'COUNTY3_',
 'COUNTY3_ID',
 'COUNTY',
 'Shape_Leng',
 'Shape_Area',
 'geometry']

In [46]:
merged_gdf = geo_df.merge(df, left_on='COUNTY', right_on='County Name')

In [47]:
list(merged_gdf.columns)

['OBJECTID',
 'AREA',
 'PERIMETER',
 'COUNTY3_',
 'COUNTY3_ID',
 'COUNTY',
 'Shape_Leng',
 'Shape_Area',
 'geometry',
 'Coun- ty Code',
 'County Name',
 'Agriculture, forestry and fishing',
 'Mining and quarrying',
 'Manufacturing',
 'Electricity supply',
 'Water supply; waste collection',
 'Construction',
 'Wholesale and retail trade; repair of motor vehicles',
 'Transport and storage',
 'Accom- modation and food service activities',
 'Informa- tion and communi- cation',
 'Financial and insurance activities',
 'Real estate activities',
 'Profes- sional, technical and support services',
 'Public admin- istration and defence',
 'Education',
 'Human health and social work activities',
 'Other service activities',
 'FISIM1',
 'Total']

In [52]:
null_sum =merged_gdf.isnull().sum()
print(null_sum)

OBJECTID                                                0.0
AREA                                                    0.0
PERIMETER                                               0.0
COUNTY3_                                                0.0
COUNTY3_ID                                              0.0
COUNTY                                                  0.0
Shape_Leng                                              0.0
Shape_Area                                              0.0
Coun- ty Code                                           0.0
County Name                                             0.0
Agriculture, forestry and fishing                       0.0
Mining and quarrying                                    0.0
Manufacturing                                           0.0
Electricity supply                                      0.0
Water supply; waste collection                          0.0
Construction                                            0.0
Wholesale and retail trade; repair of motor vehicles    0.0
Transport and storage                                   0.0
Accom- modation and food service activities             0.0
Informa- tion and communi- cation                       0.0
Financial and insurance activities                      0.0
Real estate activities                                  0.0
Profes- sional, technical and support services          0.0
Public admin- istration and defence                     0.0
Education                                               0.0
Human health and social work activities                 0.0
Other service activities                                0.0
FISIM1                                                  0.0
Total                                                   0.0
dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_12204\689326713.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  null_sum =merged_gdf.isnull().sum()

In [53]:
nan_count = merged_gdf['Manufacturing'].isnull().sum()
print(f"Number of NaN values in 'Manufacturing': {nan_count}")

Number of NaN values in 'Manufacturing': 0

In [54]:
print(merged_gdf['Manufacturing'].dtype)

int64

In [55]:
print(merged_gdf.is_valid.sum())

# Check for any NaNs in the geometry column
print(merged_gdf.geometry.isnull().sum())

0
0

In [58]:
merged_gdf['Manufacturing'] = merged_gdf['Manufacturing'].astype(int)

In [60]:
print(merged_gdf.head())

Empty GeoDataFrame
Columns: [OBJECTID, AREA, PERIMETER, COUNTY3_, COUNTY3_ID, COUNTY, Shape_Leng, Shape_Area, geometry, Coun- ty Code, County Name, Agriculture, forestry and fishing, Mining and quarrying, Manufacturing, Electricity supply, Water supply; waste collection, Construction, Wholesale and retail trade; repair of motor vehicles, Transport and storage, Accom- modation and food service activities, Informa- tion and communi- cation, Financial and insurance activities, Real estate activities, Profes- sional, technical and support services, Public admin- istration and defence, Education, Human health and social work activities, Other service activities, FISIM1, Total]
Index: []

[0 rows x 30 columns]